language: go

dist: trusty

go:
  - 1.11.x
  - 1.12.x
  - 1.13.x

sudo: false

env:
  global:
    - CONSUL_VERSION="1.6.2"
    - GO111MODULE=on

install:
  - wget "https://releases.hashicorp.com/consul/${CONSUL_VERSION}/consul_${CONSUL_VERSION}_linux_amd64.zip"
  - mkdir -p $HOME/bin
  - unzip -d $HOME/bin consul_${CONSUL_VERSION}_linux_amd64.zip
  - export PATH=$HOME/bin:$PATH
  - go mod vendor

before_script:
  - go vet ./
  - go vet

script:
  - go test -race -v
