language: go

dist: trusty

go:
  - 1.7.x
  - 1.8.x

branches:
  only:
    - master

sudo: false

install:
  - wget "https://github.com/Masterminds/glide/releases/download/v0.12.3/glide-v0.12.3-linux-amd64.tar.gz"
  - wget "https://releases.hashicorp.com/consul/0.8.3/consul_0.8.3_linux_amd64.zip"
  - mkdir -p $HOME/bin
  - tar -vxz -C $HOME/bin --strip=1 -f glide-v0.12.3-linux-amd64.tar.gz
  - unzip -d $HOME/bin consul_0.8.3_linux_amd64.zip
  - export PATH="$HOME/bin:$PATH"
  - glide up

before_script:
  - go vet ./

script:
  - go test -v
