language: go

dist: trusty

go:
  - 1.9.x

sudo: false

install:
  - wget "https://github.com/Masterminds/glide/releases/download/v0.13.1/glide-v0.13.1-linux-amd64.tar.gz"
  - wget "https://releases.hashicorp.com/consul/1.0.0/consul_1.0.0_linux_amd64.zip"
  - mkdir -p $HOME/bin
  - tar -vxz -C $HOME/bin --strip=1 -f glide-v0.13.1-linux-amd64.tar.gz
  - unzip -d $HOME/bin consul_1.0.0_linux_amd64.zip
  - export PATH="$HOME/bin:$PATH"
  - glide cc
  - glide install
  - |
    set -e
    mkdir fakego
    cd fakego
    mkdir pkg bin
    ln -s ../vendor src
    TMPGOPATH=$GOPATH
    export GOPATH=$(pwd)
    cd src
    go install github.com/hashicorp/consul/test/porter/cmd/porter
    export PATH=$PATH:$GOPATH/bin
    cd ../..
    export GOPATH=$TMPGOPATH

before_script:
  - go vet ./

script:
  - porter go test -v
