[prune]
  go-tests = true
  unused-packages = true
  non-go = true

[[constraint]]
  name = "github.com/hashicorp/consul"
  version = ">=v1.5.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "v1.3.*"