[[constraint]]
  name = "github.com/hashicorp/consul"
  version = ">=v1.0.1"
[[constraint]]
  name = "github.com/stretchr/testify"
  version = "v1.1.*"
[[constraint]]
  name = "github.com/renstrom/shortuuid"
  version = "v2.0.*"
